In [2]:
import torch
import numpy as np

In [147]:
a = torch.tensor([3,1,1,5,1,4],dtype=torch.int8)   # dtype=torch.long
print(a)
print(a.size())

tensor([3, 1, 1, 5, 1, 4], dtype=torch.int8)
torch.Size([6])


In [ ]:
torch.tensor((2,2), dtype=torch.float)

torch.zero((2,2)) # 初始化元素为0
torch.ones((2,2)) # 初始化元素为1

torch.rand(2,2) #随机初始化[0,1]
torch.randn(2,2) #随机初始化, 0-均值 1-方差

—— ﹡.size()与﹡.shape：显示形状

In [93]:
a = torch.tensor([2,2])
b = np.array([2,2])
print(a.size())
print(b.shape)

torch.Size([2])
(2,)


—— *.transpose()：转置

    tensor一次只能对两个维度进行转置，但numpy可以同时对多个维度进行转置

In [152]:
a = torch.arange(30).reshape(2, 3, 5)
print(a.transpose(1, 0))

tensor([[[ 0,  1,  2,  3,  4],
         [15, 16, 17, 18, 19]],

        [[ 5,  6,  7,  8,  9],
         [20, 21, 22, 23, 24]],

        [[10, 11, 12, 13, 14],
         [25, 26, 27, 28, 29]]])


In [154]:
# 交换第0维度和第1维度的数据
a = np.arange(30).reshape(2, 3, 5)  # 对7来说，[0,1,2]
print(a)
print()
print(a.transpose(1, 0, 2))   # 对7来说，[1,0,2]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]

[[[ 0  1  2  3  4]
  [15 16 17 18 19]]

 [[ 5  6  7  8  9]
  [20 21 22 23 24]]

 [[10 11 12 13 14]
  [25 26 27 28 29]]]


1、numpy转torch

—— torch.from_numpy(*)

In [74]:
a = np.arange(8)
b = torch.from_numpy(a)
b

tensor([0, 1, 2, 3, 4, 5, 6, 7], dtype=torch.int32)

2、torch转numpy

In [78]:
a = torch.tensor(8)
b = np.arange(a)
b

array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64)

—— torch.max(﹡,n,keepdim) ：返回最大值和其index ★

In [160]:
anch_ious=torch.Tensor([[1,2,3],[4,5,6],[7,8,9]])

b=torch.max(anch_ious.data, 1)
print(b[0])  # 最大值
print(b[1])  # index

tensor([3., 6., 9.])
tensor([2, 2, 2])


In [161]:
anch_ious=torch.Tensor([[1,2,3],[4,5,6],[7,8,9]])

b=torch.max(anch_ious, 1, keepdim=True)   # 保持原形状
print(b[0])
print(b[1])

b=b[1].squeeze(1)
print(b)
print(anch_ious[list(range(anch_ious.size(0))),b])

tensor([[3.],
        [6.],
        [9.]])
tensor([[2],
        [2],
        [2]])
tensor([2, 2, 2])
tensor([3., 6., 9.])


##### 矩阵形状

—— *.squeeze()：保持原元素，消去维度为1的维度；对二维矩阵没有影响

—— *.unsqueeze(n)：在第n维度增加1个维度

In [19]:
a = torch.rand([3,1,2])
print(a.size())
print(a)

torch.Size([3, 1, 2])
tensor([[[0.7216, 0.1696]],

        [[0.3087, 0.7559]],

        [[0.6273, 0.2395]]])


In [20]:
a2 = a.squeeze()
print(a2.size())
print(a2)

torch.Size([3, 2])
tensor([[0.7216, 0.1696],
        [0.3087, 0.7559],
        [0.6273, 0.2395]])


In [25]:
a3 = a.unsqueeze(1)
print(a3.size())
print(a3)

torch.Size([3, 1, 1, 2])
tensor([[[[0.7216, 0.1696]]],


        [[[0.3087, 0.7559]]],


        [[[0.6273, 0.2395]]]])


##### 数据与梯度

—— requires_grad = True时，表示声明的是梯度。必须浮点型数据才可以使用梯度

—— *.backward.()：使用链式法则反向求导，如果对非标量*求导，函数需要额外指定grad_tensors，grad_tensors的shape必须和*的相同

    grad_fn:表示获取方式

—— *.grad：获取梯度

—— *.data：获取数据

In [63]:
# 案例一
x = torch.tensor([16.0],requires_grad=True)
print(x)   # 具有梯度的x
print(x.data)   # 没有梯度的x.data
y=x**2
y.backward()
print(x.grad)

tensor([16.], requires_grad=True)
tensor([16.])
tensor([32.])


In [62]:
# 案例二
x = torch.ones(2,2,requires_grad=True)
y = x*2
print(y)
z = y.mean()   # z=1\4（yy1+yy2+yy3+yy4）
print(z)
z.backward()   # 对z求x的偏导
print(x.grad)   # 梯度 = 偏导*z

tensor([[2., 2.],
        [2., 2.]])
tensor(2., grad_fn=<MeanBackward1>)
tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])


—— .view() 和 .reshape()

In [66]:
a = np.arange(8)
b = a.reshape(2,2,2)
print('b', b)

b = torch.tensor(a)
c = b.view(2,2,2)
print('c',c)

b [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
c tensor([[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]], dtype=torch.int32)
